### ISSUE TITLE
Refactor Wordpress/WooCommerce - Cleaning and corrections

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-wordpress#43]
### Plugin wordpress

1. Clean up old and unused code of the plugin.
2. Change names of api_host and api_key to server and user_key in the UI because the stored data is from doomanager, not from API.

### Items_transformation

1. product_category -> En la linea 35 se genera un sentry porque puede ser nil, hay que comprobar el valor antes de hacer un Map.get  https://doofindercom.sentry.io/issues/4213874882/?project=5681317&query=is%3Aunresolved+assigned%3Ame&referrer=issue-stream&statsPeriod=14d&stream_index=0
2. Change in the categories the field name to title.
`
Cambiar como se asigna en el items_transformation para poder usar el campo title una vez indexado
`
![image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/04a76f53-b422-46b0-826d-673839badde9)

### Doofeeds

1. La línea feed_type = Keyword.get(opts, :feed_type) || "post" habría que sustituirla por: Keyword.get(opts, :feed_type, "post") 
2. Add error clauses specific for 400 of Wordpress API. In WooCommerce returns an empty list instead of an error.Description by @eduardogomez97 
`
Es un feed que en realidad ya tengo visto, es de doofeeds. Es que cuando se hace una llamada a la API para las categorías se va hacién el scroll page y se va a haciendo peticiones por páginas, lo que pasa es que la API de Wordpress en el caso de las categorías en vez de devolver una lista vacía cuando no existe. Lo que devuelve es un 400. Entonces es simplemente que cuando nos devuelva un 400 devolver un {:ok, %{}}
`
https://doofindercom.sentry.io/issues/4213853167/?project=5681317&query=is%3Aunresolved+assigned%3Ame&referrer=issue-stream&statsPeriod=14d&stream_index=1
![image (57)](https://github.com/doofinder/doofinder-wordpress/assets/46921456/eb260e5b-7575-4e5e-b01a-f9be32d43dac)
![image (58)](https://github.com/doofinder/doofinder-wordpress/assets/46921456/a1b90435-bf0f-4f90-916b-b4edf24c8996)

### Doomanager

1.  Solve sentry related with multiindices https://doofindercom.sentry.io/issues/4201940915/?project=6152838&query=is%3Aunresolved+assigned%3Ame&referrer=issue-stream&statsPeriod=14d&stream_index=2

blocked by https://github.com/doofinder/doofinder-wordpress/issues/44 https://github.com/doofinder/doofinder-wordpress/issues/54 https://github.com/doofinder/doofinder-wordpress/issues/55
blocks https://github.com/doofinder/doofinder-woocommerce/issues/131

**Comment by pedromcp90** [comment]
I've been trying to reproduce the multi-indices error, but I couldn't, seems like it should be resolved by now.
[Link to sentry issue](https://doofindercom.sentry.io/issues/4201940915/)
