### ISSUE TITLE
Investigate the cron in wordpress core

### ISSUE THREAD

**Issue by eduardogomez97** [doofinder/doofinder-wordpress#60]
Related to https://github.com/doofinder/doofinder-wordpress/issues/54

I have tried to implement the update on save integration with the wordpress cron. But it presents the same problems as in prestashop, it does not let us use a custom concurrency associating it in php and the associated task does not run because it seems that it would have to be globalized.

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/c93c0699-985f-4b32-8415-05ff9ceb313c)

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/631ff002-08d4-48ff-9c51-3b6a85c904cd)

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/b3c0348b-6619-4793-9afe-e0c2a14f6fb8)

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/8205596a-599c-4d9f-8b3b-8d167a23ff7a)

**Comment by pedromcp90** [comment]
Done in [doofinder-wordpress/pull/75](https://github.com/doofinder/doofinder-wordpress/pull/75)
