### ISSUE TITLE
Migration of users from Wordpress/Woocommerce plugins to the new one when upgrading

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-wordpress#65]
Users of current Wordpress and Woocommerce plugins have settings that should be kept when upgrading.

Blocked by #43

**Comment by eduardogomez97** [comment]
The main idea for the migration is to use the function that detects when the plugin is being updated to launch a migrate as in the example picture:

![Image](https://github.com/doofinder/doofinder-wordpress/assets/22339368/427446ca-207e-4aea-ab25-38edaf724c92)

This function should take care of the 3 most important steps which are:

1.- Sanitize the database to clean the deprecated data and adapt the new ones.
2.- Check if there is a credentials called doofinder for the REST API and if not, create them.
3.- Send to a doomanager endpoint a payload with the credentials and the new indexes (like the sign up one).

On the part of doomanager this end point should add to the store.options the credentials. And create the relevant indexes to the wordpress type. 

With these simple steps when a customer upgrades to the new version will have his store fully functional and adapted to the new workflow.

@pedromcp90
