### ISSUE TITLE
Wordpress/WooCommerce - Add Manual Indexation for updated products in plugin

### ISSUE THREAD

**Issue by albertodoofinder** [doofinder/doofinder-wordpress#72]
Add a button that calls a controller from the admin of Wordpress/WooCommerce that updates directly the products waiting to be updated using update on save in Doofinder.

@CristobalDolz

Related issue https://github.com/doofinder/dfcommon/issues/583

**Comment by pedromcp90** [comment]
I've Added a buton next to the update on save selector in the settings page:
![image](https://github.com/doofinder/doofinder-wordpress/assets/1659534/5a6188e4-371d-4df6-9483-b2bd8a23f679)
![image](https://github.com/doofinder/doofinder-wordpress/assets/1659534/046875a3-6dc7-44f9-8ff5-b0ff3940553c)
