### ISSUE TITLE
[Wordpress] sale_price de producto padre

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-wordpress#88]
Parece que no estamos indexando correctamente el sale price del producto padre de los productos configurables.

El producto padre, debería indexar el sale_price más bajo del grupo de variaciones. Es decir, que si en el grupo de variaciones, uno de ellas tiene un descuento, el producto padre debería incluirlo también.

**Comment by ogomezba** [comment]
@kataklanka Hola Alfonso! Este problema está ya solucionado en la última release que hemos puesto en producción. Si hay cualquier problema, coméntame!
