### ISSUE TITLE
Update doofinder-wordpress status in the repo

### ISSUE THREAD

**Issue by brunovesar** [doofinder/doofinder-wordpress#89]
This repo is not being mantained and I think we're only using the [doofinder/doofinder-woocommerce](https://github.com/doofinder/doofinder-woocommerce) repo.
Should we archive this?
Or at least I think we should disencorage anyone to use it and point to the maintained plugin instead.

@agutierrezrodriguez What do you think?
CC @sofia-doofinder

**Comment by agutierrezrodriguez** [comment]
I agree!

**Comment by brunovesar** [comment]
In that case I'll add a comment in the readme and then archive the repo
