### ISSUE TITLE
[Wordpress] Analyze Make plugin compatible with woocommerce market

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-wordpress#91]
Producto necesita una estimación del tiempo que nos llevaría ajustar el plugin de woocommerce para que sea compatible con woocommerce marketplace. Han intentado subir el plugin y este ha sido el resultado de los errores:
https://product-build.woocommerce.com/v1/?action=get-report&secret=63433bf8d7bc194d6055665ef3bd2fd000.32464983&queue_item_id=697155

**Comment by eduardogomez97** [comment]
After analyzing the exchange rates, most of them are easy, but there are some that are a bit more delicate. @IgnacioPursalsZ

The estimate we have proposed is one week. To have several days to do complete testing of the whole module and deployment.
